---
#
# project meta-data used for various project tasks like building gem packages
#
name: antlr3
version: "1.9.2"
antlr_version: "3.5"
license: "BSD"

summary: |-
  Fully-featured ruby parser generation for ANTLR version 3.
author: Kyle Yetter
email: kcy5b@yahoo.com
homepage: http://antlr.ohboyohboyohboy.org/

has_rdoc: true
rubyforge_project: antlr3
executables: antlr4ruby

development_dependencies: [rspec]
requirements: [java]
required_ruby_version: ">= 1.8.7"

doc:
  .type: group
  yard: path:doc/api
  options:
    - '--incremental'
    - '-r'
    - 'README.txt'
    - '--protected'
    - '--private'
  files:
    .type: pathlist
    include:
      - lib/**/*.rb
    exclude:
      - lib/antlr3/token/*.rb

guide:
  .type: group
  input: path:doc/guide/source
  output: path:doc/guide/html
  template: doc/guide/erb/template.erb
  menu: doc/guide/source/guide.yaml
  changelog: doc/guide/source/changelog.yaml

package:
  .type: group
  base: path:pkg
  name: $(name)-$(version)
  files:
    .type: pathlist
    include:
      - bin/antlr4ruby
      - lib/**/*.rb
      - test/unit/**/*
      - test/functional/*/*.rb
      - templates/*.stg
      - samples/CPP.g
      - samples/ANTLRv3Grammar.g
      - samples/JavaScript.g
      - samples/standard/**/*
      - "*.txt"
      - "*.rdoc"
      - java/antlr-full-$(antlr_version).jar
      - java/*.java
      - dev-lib/dist/rakefile
    exclude:
      - DEVELOPER-README.txt
      - lib/antlr3/token/*.rb
  zip:
    .type: group
    dir:   path:pkg/zip/$(name)-$(version)
    ext:   .zip
    files:
      .type: pathlist
      include: 
        - dev-lib/dist/setup.rb
        - dev-lib/dist/pre-setup.rb
    relocations:
      - - lib/antlr3.rb
        - "%f.pre"
      - - java/*
        - data/antlr4ruby/%f
      - - templates/*
        - data/antlr4ruby/%p
      - - samples/**/*
        - doc/%p
      - - dev-lib/dist/*
        - "%f"
  gem:
    .type: group
    dir:    path:pkg/gem
    ext:    .gem
    files:
      .type: pathlist
      include: []
    relocations:
      - - dev-lib/dist/rakefile
        - rakefile
  
#
# important paths in the project tree
#
antlr:
  .type: pathmap
  jar: java/antlr-full-$(antlr_version).jar
  templates: java/org/antlr/codegen/templates/Ruby
  targets: java/org/antlr/codegen
  target: java/RubyTarget.java

isolate:
  .type: pathmap
  config: config/isolate.rb
  gems: vendor/gems

test:
  .type: pathmap
  unit: test/unit
  functional: test/functional
  performance: test/performance
  log: log/test.log
  results: log
  
rake_tasks: path:dev-lib/tasks
dev_lib: path:dev-lib
lib: path:lib
java: path:java
functional_testing: path:test/functional

#
# project file lists for various purposes
#
lib_jars:
  - antlr-2.7.7.jar
  - antlr-runtime-$(antlr_version).jar
  - stringtemplate-$(antlr_version).jar

unit_tests:
  .type: pathlist
  include:
    - test/unit/*.rb

functional_tests:
  .type: pathlist
  include:
    - test/functional/*/*.rb

templates:
  .type: pathlist
  include:
    - templates/*.stg

grammars:
  .type: pathlist
  include: []

#
# project environment setup
#
load:
  - dev-lib/core-ext/**/*.rb

load_path:
  - lib
  - dev-lib
  - vendor

system_path:
  - scripts
  - bin
  - vendor/gems/ruby-1.8/bin

# these are required after the gem-neutral environment is established
# via $project.load_environment
environment_require:
  - pp
  - ansi-color
  - inflection
